# Generated by Django 5.2.8 on 2025-11-17 00:00

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(upload_to=api.models.document_upload_path),
        ),
    ]
