# Generated by Django 5.2.8 on 2025-12-08 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
